# makeCacheMatrix
# The function creates a "matrix" object that can cache its inverse.
# The object saves the "matrix" to variable x.
# The object saves the "inverse" to variable t.
# kur: sets the "matrix" and resets its cached "inverse"
# al: returns the "matrix"
# kurCozum: saves the "solve" value
# alCozum: returns its cached "inverse" value

makeCacheMatrix <- function(x = matrix()) {
  t <- NULL
  kur <- function(y) {
    x <<- y
    t <<- NULL
  }
  al <- function() {
    x
  }
  kurCozum <- function(solve) {
    t <<- solve
  }
  alCozum <- function() {
    t
  }
  list(kur = kur, al = al, kurCozum = kurCozum, alCozum = alCozum)
}

# Function cacheSolve gets the inversed matrix from a special object created by makeCacheMatrix.
# The function takes an object generated by the function makeCacheMatrix, 'x', checks if the inverse value is 
# cached and the cached value is returned when called.
# If the cached value is not returned, function cacheSolve calculates the inverse value of the matrix.
# The method "kurCozum" saves the inverse value in 'x' cache and returns the result.

cacheSolve <- function(x, ...) {
  t <- x$alCozum()
  if(!is.null(t)) {
    message("getting cached data")
    return(t)
  }
  data <- x$al()
  t <- solve(data, ...)
  x$kurCozum(t)
  t
}
 
# Test cases


x <- makeCacheMatrix(matrix(1:4,12))
x$al()
x$alCozum()
x$kur(matrix(5:2,2))
x$al()
cacheSolve(x)
cacheSolve(x)
x$alCozum()
z = x$alCozum()
x$al() %*% z
